using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class LevelText : MonoBehaviour
{
    public int initiallevel;	//飑l单
    private int currlevel; //{b旱ク

    // Start is called before the first frame update
    void Start()
    {
        //]w飑lだ计
        currlevel = initiallevel;
    }

    public void AddScoreAndDisplay()
    {
        //C砑W[だ计
        currlevel += 1;
        //陪ボ(笈text氦濡r)
        GetComponent<Text>().text = "Level: " + currlevel.ToString();

    }

    // Update is called once per frame
    void Update()
    {

    }
}
