using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ScoreText : MonoBehaviour
{
    public int initialScore;	//飑lだ计
    public int addScorePerSec; //C砑W[氦兰
    private int currScore; //{b氦兰

    // Start is called before the first frame update
    void Start()
    {
        //]w飑lだ计
        currScore = initialScore;
    }
    void AddScoreAndDisplay()
    {
        //C砑W[だ计
        currScore += addScorePerSec;

        //陪ボ(笈text氦濡r)
        GetComponent<Text>().text = "Score: " + currScore.ToString();
    }

    public void DestoryRocky()
    {
        AddScoreAndDisplay();
    }
    // Update is called once per frame
    void Update()
    {

    }
}
