using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class TimeText : MonoBehaviour
{
    public int initialTime;	//飑lだ计
    public int addTimePerSec; //C砑W[氦兰
    private int currTime; //{b氦兰

    // Start is called before the first frame update
    void Start()
    {
        //]w飑lだ计
        currTime = initialTime;
        InvokeRepeating("AddScoreAndDisplay", 1f, 1f);
        
        //C愆IsAddScoreAndDisplay()
        
    }
    void AddScoreAndDisplay()
    {
        //C砑W[だ计
        currTime += addTimePerSec;

        //陪ボ(笈text氦濡r)
        GetComponent<Text>().text = "Time: " + currTime.ToString();
    }
    public void Pause()
    {
        CancelInvoke();
    }
    public void Continue()
    {
        InvokeRepeating("AddScoreAndDisplay", 1f, 1f);
    }
    // Update is called once per frame
    void Update()
    {
        
    }
}
